import { BigNumber } from 'bignumber.js';
import { GiverOptions, KeysOptions } from '../cli/lib/configuration';
export declare const loadJSONFromFile: (filePath: string) => any;
export declare const loadBase64FromFile: (filePath: string) => string;
export declare const convertCrystal: (amount: BigNumber.Value, dimension: 'nano' | 'ton') => BigNumber;
export declare let network: string;
export declare const setNetwork: (newNetwork: string) => void;
export declare const getRandomNonce: () => number;
export declare const ZERO_ADDRESS = "0:0000000000000000000000000000000000000000000000000000000000000000";
export declare const EMPTY_TVM_CELL = "te6ccqEBAQEAAqAAAA==";
export declare const nodeUrl: () => string;
export declare const giver: () => GiverOptions;
export declare const keys: () => KeysOptions;
